#! /usr/bin/python 
  
def scanFiles(directoryName):
  import os
  fileList = os.listdir(directoryName)
  fileList = map(lambda f: os.path.join(directoryName, f), fileList)
  fileList = map(lambda f: os.path.normcase(f), fileList)
  fileList = filter(lambda f: os.path.isfile(f), fileList)# and \
  #fileList = filter(lambda f: os.path.splitext(f)[1].lower()[1:] == 'min', fileList)# and \
  fileList = filter(lambda f: os.path.splitext(f)[1].lower()[1:] == 'skim', fileList)# and \
  return fileList

if __name__ == '__main__':

  import sys
  import os
  if len(sys.argv) < 2 :
    print 'arguments error'
    sys.exit()

  dir_name = os.path.normpath(os.path.abspath(sys.argv[1]))
  print dir_name
  fileList = scanFiles(dir_name)
  dst_name = os.path.join(dir_name, 'analy')

  if os.path.exists(dst_name) is False :
    print dst_name + ' is created now'
    os.mkdir(dst_name)

  from v12analyzeEtappb  import AnalyzeEtappb
  #from v14analyzeEtappb  import AnalyzeEtappb
  #from v01analyzePi0ppb  import AnalyzeEtappb

  print fileList
  analyze = AnalyzeEtappb(fileList)
  analyze.loop()
  analyze.finalize()
  del analyze
