#!/usr/bin/python
import re
import os
import commands
import time

cmdDir = './macDir/'

def executeCmd():
  commands.getoutput('rm -f run*.*')
  print 'exe ++++++++++++++++++++++++++'  
  print 'run  jobs'
  commands.getoutput('./subJobs')

  timeClock = 0
  while 1:
    time.sleep(60)
    timeClock += 1
    print timeClock, 'minutes lasted'
    if commands.getoutput('./trkJobs') == 'Finished':
      print 'jobs finished'
      break
    
  
  
def makeMac(position_x = -1.5, position_y = 0, position_z = -95, 
    angle_x = 0.5, angle_y = 0.3, angle_z = 0.2,
    particle = 'pi-', energy = '900'):

  position_r = '%d' % position_z
  position = '%.1f %d %d' % (position_x, position_y, position_z)
  angle_r = '%d_%d_%d' % (angle_x * 10, angle_y * 10, angle_z * 10)
  angle = '%.1f %.1f %.1f' % (angle_x, angle_y, angle_z)
  
  particle_pattern = '(pi|k|kpi)(-?(\+?)0?)$'
  energy_pattern = '([0-9]{3,4})\s+(MeV$)'
  position_pattern = '(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(cm$)'
  angle_pattern = '([0-1])\.([0-9]{1,3})\s+([0-1])\.([0-9]{1,3})\s+([0-1])\.([0-9]{1,3})$'
  file_pattern = '(pi|k|kpi)_E([0-9]{3,4})_P([0-9]{1,2})_A([0-9]{1,2})\.(root$)'
  
  rootFile = particle + "_E" + energy \
      + "_P" + position_r + "_A" + angle_r + ".root"
  
  aFile = open( 'source.mac', "r")
  allLines = aFile.readlines()
  aFile.close()
  
  #print allLines
  nl = 0
  for eachLine in allLines:
    if eachLine.startswith( "/gun/particle"):
      allLines[nl] = re.sub( particle_pattern, particle, eachLine, 1)
    if eachLine.startswith( "/gun/energy"):
      allLines[nl] = re.sub( energy_pattern, energy + " MeV", eachLine, 1)
    if eachLine.startswith( "/gun/position"):
      allLines[nl] = re.sub( position_pattern, position + " cm", eachLine, 1)
    if eachLine.startswith( "/gun/direction"):
      allLines[nl] = re.sub( angle_pattern, angle, eachLine, 1)
    if eachLine.startswith( "/runfile/name"):
      allLines[nl] = re.sub( file_pattern, rootFile, eachLine, 1)
      
      #print "substitute paricle: " + particle 
      #print "substitute energy: " + energy + "Mev"
      #print "substitute position: " + position + " cm"
      #print "substitute direction: " + angle
      #print "substitute root file name: " + rootFile 
    nl = nl + 1
  
  global cmdDir
  newMac = particle + "_E" + energy \
      + "_P" + position_r + "_A" + angle_r + ".mac"
  newFile = open( cmdDir + newMac, "w")
  newFile.writelines( allLines)
  newFile.close()

def run():
  for position_z in range(-50, -96, -5):
    cmd = 'rm macDir/* -f'
    os.system(cmd)
    print 'position_z: ', position_z
    
    for angle_y in range(0, 25, 4):
      for angle_z in range(-10, 11, 2):
        makeMac(-1.5, 0, position_z, 0.5, angle_y/10.0, angle_z/10.0, 'pi-', '900')
        
    executeCmd()
  
if __name__ == "__main__":
  run()
